version: '3'
services:
  web:
    image: myphp
    ports:
      - 80:80
    volumes:
      - ./exhibition:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: exhibition
      MYSQL_ROOT_PASSWORD: root@0000
      MYSQL_USER: user
      MYSQL_PASSWORD: user@0000
    volumes:
      - ./DB_data:/var/lib/mysql  